---

  - name: Generate SSH Key
    tags:
      - git
    user:
      name: "{{ansible_env.USER}}"
      generate_ssh_key: yes
      ssh_key_file: .ssh/id_rsa

  - name: Set git username
    tags:
      - git
    git_config:
      name: user.name
      value: "{{git_username}}"
      scope: global

  - name: Set git email
    tags:
      - git
    git_config:
      name: user.email
      value: "{{git_email}}"
      scope: global
    when: git_email is defined

  - name: Set git autocrlf
    tags:
      - git
    git_config:
      name: core.autocrlf
      value: input
      scope: global

  - name: Create git excludes file
    tags:
      - git
    template:
      src: excludes-file.j2
      dest: "{{ansible_env.HOME}}/.gitexcludes"
      mode: 0640

  - name: Set git excludesfile
    tags:
      - git
    git_config:
      name: core.excludesfile
      value: "{{ansible_env.HOME}}/.gitexcludes"
      scope: global

  - name: Create git commit template
    tags:
      - git
    template:
      src: commit-template.j2
      dest: "{{ansible_env.HOME}}/.gitcommit"
      mode: 0640

  - name: Set git commit template
    tags:
      - git
    git_config:
      name: commit.template
      value: "{{ansible_env.HOME}}/.gitcommit"
      scope: global
